services:
    _defaults:
        autoconfigure: true
        public: true

    BrockhausAg\ContaoReleaseStagesBundle\EventListener\DataContainer\EditButtonsCallback:

    BrockhausAg\ContaoReleaseStagesBundle\Mapper\Config\ConfigMapper:

    BrockhausAg\ContaoReleaseStagesBundle\Logger\Logger:
        arguments:
        - '@logger'

    BrockhausAg\ContaoReleaseStagesBundle\System\SystemConfig:
        arguments:
            - '%kernel.project_dir%'
            - '@BrockhausAg\ContaoReleaseStagesBundle\Mapper\Config\ConfigMapper'
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logger\Logger'
        calls:
            - loadConfig: []

    BrockhausAg\ContaoReleaseStagesBundle\Logic\Timer:
        arguments:
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logic\Config'
        shared: false

    BrockhausAg\ContaoReleaseStagesBundle\Logic\Synchronizer\ScriptFileSynchronizer:
        arguments:
            - '%kernel.project_dir%'
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logic\FTP\FTPConnector'
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logic\Config'
        shared: false

    BrockhausAg\ContaoReleaseStagesBundle\Logic\Versioning\Versioning:
        arguments:
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logic\Database\Database'
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logger\Logger'
        shared: false

    BrockhausAg\ContaoReleaseStagesBundle\Logic\Config:
        arguments:
            - '%kernel.project_dir%'
            - '@BrockhausAg\ContaoReleaseStagesBundle\System\SystemConfig'
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logger\Logger'

    BrockhausAg\ContaoReleaseStagesBundle\EventListener\DataContainer\ReleaseStages:
        arguments:
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logic\Timer'
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logic\Synchronizer\ScriptFileSynchronizer'
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logic\Versioning\Versioning'
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logic\Backup\BackupCreator'
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logic\Database\DatabaseCopier'
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logic\FileServer\FileServerCopier'
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logic\Synchronizer\StateSynchronizer'
        shared: false

    BrockhausAg\ContaoReleaseStagesBundle\Logic\Database\DatabaseCopier:
        arguments:
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logic\Database\Database'
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logic\Database\DatabaseProd'
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logic\Config'
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logic\Database\Migrator\MigrationBuilder'
        shared: false

    BrockhausAg\ContaoReleaseStagesBundle\Logic\Database\Database:
        arguments:
            - '@database_connection'
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logic\Config'

    BrockhausAg\ContaoReleaseStagesBundle\Logic\Synchronizer\StateSynchronizer:
        arguments:
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logic\Database\Database'
        shared: false

    BrockhausAg\ContaoReleaseStagesBundle\Logic\Database\DatabaseProd:
        arguments:
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logic\Config'
        calls:
            - setUp: []

    BrockhausAg\ContaoReleaseStagesBundle\Logic\FileServer\FileServerCopier:
        arguments:
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logic\Database\Database'
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logic\Config'
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logic\Local\FileServerLocalCopier'
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logger\Logger'
        shared: false

    BrockhausAg\ContaoReleaseStagesBundle\Logic\Local\FileServerLocalCopier:
        arguments:
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logger\Logger'
        shared: false

    BrockhausAg\ContaoReleaseStagesBundle\Logic\FTP\FTPConnector:
        arguments:
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logic\Config'
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logger\Logger'
        calls:
            - setUp: []
        shared: false

    BrockhausAg\ContaoReleaseStagesBundle\Logic\SSH\SSHConnector:
        arguments:
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logic\Config'
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logger\Logger'
        calls:
            - setUp: []
        shared: false

    BrockhausAg\ContaoReleaseStagesBundle\Logic\FileServer\LocalLoader:
        arguments:
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logic\Config'
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logger\Logger'

    BrockhausAg\ContaoReleaseStagesBundle\Logic\FileServer\Compressor\Compressor:
        arguments:
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logger\Logger'

    BrockhausAg\ContaoReleaseStagesBundle\Logic\Backup\BackupCreator:
        arguments:
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logic\SSH\SSHConnector'
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logic\Config'
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logic\Poller'
        shared: false

    BrockhausAg\ContaoReleaseStagesBundle\Logic\Poller:
        arguments:
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logic\FTP\FTPConnector'
        shared: false
