services:
    _defaults:
        autoconfigure: true
        public: true

    BrockhausAg\ContaoReleaseStagesBundle\Mapper\Config\MapConfig:

    BrockhausAg\ContaoReleaseStagesBundle\Logger\Log:
        arguments:
        - '@logger'

    BrockhausAg\ContaoReleaseStagesBundle\System\SystemConfig:
        arguments:
            - '%kernel.project_dir%'
            - '@BrockhausAg\ContaoReleaseStagesBundle\Mapper\Config\MapConfig'
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logger\Log'
        calls:
            - loadConfig: []

    BrockhausAg\ContaoReleaseStagesBundle\System\ScriptFileSynchronizer:
        arguments:
            - '%kernel.project_dir%'
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logic\FTP\FTPConnector'
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logic\IO'

    BrockhausAg\ContaoReleaseStagesBundle\System\SystemBuilder:
        arguments:
            - '@BrockhausAg\ContaoReleaseStagesBundle\System\ScriptFileSynchronizer'
        calls:
            - build: []

    BrockhausAg\ContaoReleaseStagesBundle\Logic\Versioning\Versioning:
        arguments:
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logic\Database\Database'
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logger\Log'

    BrockhausAg\ContaoReleaseStagesBundle\Logic\IO:
        arguments:
            - '%kernel.project_dir%'
            - '@BrockhausAg\ContaoReleaseStagesBundle\System\SystemConfig'
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logger\Log'

    BrockhausAg\ContaoReleaseStagesBundle\EventListener\DataContainer\ReleaseStages:
        arguments:
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logic\Versioning\Versioning'
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logic\Backup\BackupCreator'
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logic\Database\DatabaseCopier'
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logic\FileServer\FileServerCopier'

    BrockhausAg\ContaoReleaseStagesBundle\Logic\Database\DatabaseCopier:
        arguments:
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logic\Database\Database'
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logic\Database\DatabaseProd'
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logic\IO'

    BrockhausAg\ContaoReleaseStagesBundle\Logic\Database\Database:
        arguments:
            - '@database_connection'
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logic\IO'

    BrockhausAg\ContaoReleaseStagesBundle\Logic\Database\DatabaseProd:
        arguments:
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logic\IO'
        calls:
            - setUp: []

    BrockhausAg\ContaoReleaseStagesBundle\Logic\FileServer\FileServerCopier:
        arguments:
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logic\Database\Database'
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logic\IO'
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logic\FileServer\Local\FileServerLocalCopier'
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logger\Log'

    BrockhausAg\ContaoReleaseStagesBundle\Logic\FileServer\Local\FileServerLocalCopier:
        arguments:
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logger\Log'

    BrockhausAg\ContaoReleaseStagesBundle\Logic\FTP\FTPConnector:
        arguments:
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logic\IO'
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logger\Log'
        calls:
            - setUp: []

    BrockhausAg\ContaoReleaseStagesBundle\Logic\SSH\SSHConnector:
        arguments:
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logic\IO'
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logger\Log'
        calls:
            - setUp: []

    BrockhausAg\ContaoReleaseStagesBundle\Logic\FileServer\LocalLoader:
        arguments:
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logic\IO'
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logger\Log'

    BrockhausAg\ContaoReleaseStagesBundle\Logic\FileServer\Compressor\Compressor:
        arguments:
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logger\Log'

    BrockhausAg\ContaoReleaseStagesBundle\Logic\Backup\BackupCreator:
        arguments:
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logic\SSH\SSHConnector'
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logic\IO'
            - '%kernel.project_dir%'
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logic\FTP\FTPConnector'
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logger\Log'
        calls:
            - setUp: []
