services:
    _defaults:
        autoconfigure: true
        public: true

    BrockhausAg\ContaoReleaseStagesBundle\Mapper\Config\MapConfig:

    BrockhausAg\ContaoReleaseStagesBundle\Logger\Log:
        arguments:
        - '@logger'

    BrockhausAg\ContaoReleaseStagesBundle\System\SystemConfig:
        arguments:
            - '%kernel.project_dir%'
            - '@BrockhausAg\ContaoReleaseStagesBundle\Mapper\Config\MapConfig'
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logger\Log'
        calls:
            - loadConfig: []

    BrockhausAg\ContaoReleaseStagesBundle\Logic\Versioning\VersioningLogic:
        arguments:
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logic\Database\DatabaseLogic'
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logger\Log'

    BrockhausAg\ContaoReleaseStagesBundle\Logic\IOLogic:
        arguments:
            - '%kernel.project_dir%'
            - '@BrockhausAg\ContaoReleaseStagesBundle\System\SystemConfig'
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logger\Log'

    BrockhausAg\ContaoReleaseStagesBundle\EventListener\DataContainer\ReleaseStagesEventListener:
        arguments:
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logic\Versioning\VersioningLogic'
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logic\Database\DatabaseCopierLogic'
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logic\FileServer\FileServerCopierLogic'

    BrockhausAg\ContaoReleaseStagesBundle\Logic\Database\DatabaseCopierLogic:
        arguments:
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logic\Database\DatabaseLogic'
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logic\Database\ProdDatabaseLogic'
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logic\IOLogic'
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logger\Log'

    BrockhausAg\ContaoReleaseStagesBundle\Logic\Database\DatabaseLogic:
        arguments:
            - '@database_connection'
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logic\IOLogic'

    BrockhausAg\ContaoReleaseStagesBundle\Logic\Database\ProdDatabaseLogic:
        arguments:
            - '@database_connection'
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logic\IOLogic'
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logger\Log'
        calls:
            - setUpDatabaseConnection: []

    BrockhausAg\ContaoReleaseStagesBundle\Logic\FileServer\FileServerCopierLogic:
        arguments:
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logic\Database\DatabaseLogic'
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logic\IOLogic'
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logic\FileServer\Local\LocalFileServerCopier'
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logger\Log'

    BrockhausAg\ContaoReleaseStagesBundle\Logic\FileServer\Local\LocalFileServerCopier:
        arguments:
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logger\Log'

    BrockhausAg\ContaoReleaseStagesBundle\Logic\FileServer\FTP\FTPConnection:
        arguments:
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logic\IOLogic'
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logger\Log'
        calls:
            - setUpFTPConfig: []

    BrockhausAg\ContaoReleaseStagesBundle\Logic\FileServer\LocalLoaderLogic:
        arguments:
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logic\IOLogic'
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logger\Log'

    BrockhausAg\ContaoReleaseStagesBundle\Logic\FileServer\Compressor\CompressorLogic:
        arguments:
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logger\Log'
