services:
    _defaults:
        autoconfigure: true
        public: true

    BrockhausAg\ContaoReleaseStagesBundle\Mapper\Config\MapConfig:

    BrockhausAg\ContaoReleaseStagesBundle\Logger\Log:
        arguments:
        - '@logger'

    BrockhausAg\ContaoReleaseStagesBundle\System\SystemConfig:
        arguments:
            - '%kernel.project_dir%'
            - '@BrockhausAg\ContaoReleaseStagesBundle\Mapper\Config\MapConfig'
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logger\Log'
        calls:
            - loadConfig: []

    BrockhausAg\ContaoReleaseStagesBundle\Logic\Versioning\Versioning:
        arguments:
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logic\Database\Database'
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logger\Log'

    BrockhausAg\ContaoReleaseStagesBundle\Logic\IO:
        arguments:
            - '%kernel.project_dir%'
            - '@BrockhausAg\ContaoReleaseStagesBundle\System\SystemConfig'
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logger\Log'

    BrockhausAg\ContaoReleaseStagesBundle\EventListener\DataContainer\ReleaseStages:
        arguments:
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logic\Versioning\Versioning'
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logic\Database\DatabaseCopier'
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logic\FileServer\FileServerCopier'

    BrockhausAg\ContaoReleaseStagesBundle\Logic\Database\DatabaseCopier:
        arguments:
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logic\Database\Database'
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logic\Database\ProdDatabase'
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logic\IO'
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logger\Log'

    BrockhausAg\ContaoReleaseStagesBundle\Logic\Database\Database:
        arguments:
            - '@database_connection'
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logic\IO'

    BrockhausAg\ContaoReleaseStagesBundle\Logic\Database\ProdDatabase:
        arguments:
            - '@database_connection'
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logic\IO'
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logger\Log'
        calls:
            - setUpDatabaseConnection: []

    BrockhausAg\ContaoReleaseStagesBundle\Logic\FileServer\FileServerCopier:
        arguments:
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logic\Database\Database'
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logic\IO'
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logic\FileServer\Local\LocalFileServerCopier'
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logger\Log'

    BrockhausAg\ContaoReleaseStagesBundle\Logic\FileServer\Local\LocalFileServerCopier:
        arguments:
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logger\Log'

    BrockhausAg\ContaoReleaseStagesBundle\Logic\FileServer\FTP\FTPConnection:
        arguments:
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logic\IO'
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logger\Log'
        calls:
            - setUpFTPConfig: []

    BrockhausAg\ContaoReleaseStagesBundle\Logic\FileServer\LocalLoader:
        arguments:
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logic\IO'
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logger\Log'

    BrockhausAg\ContaoReleaseStagesBundle\Logic\FileServer\Compressor\Compressor:
        arguments:
            - '@BrockhausAg\ContaoReleaseStagesBundle\Logger\Log'
